### ISSUE TITLE
JSON parse error

### ISSUE THREAD

**Issue by doug-wade** [addaleax/npm-get-top-dependents#2]
I'm trying to find the top dependents of an npm package, but the json doesn't seem to parse:

```
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: Unexpected "T" at position 0 in state START
    at Parser.proto.charError (/home/doug/workspace/npm-get-top-dependents-client/node_modules/npm-get-dependents/node_modules/jsonparse/jsonparse.js:84:16)
    at Parser.proto.write (/home/doug/workspace/npm-get-top-dependents-client/node_modules/npm-get-dependents/node_modules/jsonparse/jsonparse.js:112:23)
    at Stream.<anonymous> (/home/doug/workspace/npm-get-top-dependents-client/node_modules/npm-get-dependents/node_modules/JSONStream/index.js:21:12)
    at Stream.stream.write (/home/doug/workspace/npm-get-top-dependents-client/node_modules/through/index.js:26:11)
    at IncomingMessage.ondata (node:internal/streams/readable:754:22)
    at IncomingMessage.emit (node:events:527:28)
    at IncomingMessage.Readable.read (node:internal/streams/readable:527:10)
    at flow (node:internal/streams/readable:1011:34)
    at resume_ (node:internal/streams/readable:992:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on Stream instance at:
    at Stream.onerror (node:internal/streams/readable:773:14)
    at Stream.emit (node:events:527:28)
    at Parser.parser.onError (/home/doug/workspace/npm-get-top-dependents-client/node_modules/npm-get-dependents/node_modules/JSONStream/index.js:100:12)
    at Parser.proto.charError (/home/doug/workspace/npm-get-top-dependents-client/node_modules/npm-get-dependents/node_modules/jsonparse/jsonparse.js:84:8)
    at Parser.proto.write (/home/doug/workspace/npm-get-top-dependents-client/node_modules/npm-get-dependents/node_modules/jsonparse/jsonparse.js:112:23)
    [... lines matching original stack trace ...]
    at IncomingMessage.Readable.read (node:internal/streams/readable:527:10)
```

My code follows:

```
var getTopDependents = require('npm-get-top-dependents');

getTopDependents('bluebird', function(err, result) {
  if (err) {
    console.error(err);
  }

  console.log('top result: ', result[0]);
});
```

I also tried it with the object argument and got the same error:

```
getTopDependents({ package: 'bluebird' }, ...
```

Have I made some mistake? Is this an actual error?

**Comment by ljharb** [comment]
I'm running into the same problem.
